spring:
  application:
    name: eurekaserver  # Utilizado para identificar a comunicação entre o Eureka e o RabbitMq
  security:
    basic:
      enabled: true
    user:
      name: cursoms-eureka-user
      password: ecok-usr-eeuramssur

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false   # Utilizado para informar para o eureka não se auto registrar
    fetch-registry: false         # É false porque quem vai fazer o registry é o Gateway