spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Habilitando o Cloud Gateway
          lower-case-service-id: true  # Localizar por lower-case-service-id (caixa baixa/escrito em letra minúscula) Ex: msclientes
  security:
    oauth2:
      resourceserver:
        jwt:  # Alterada a porta para rodar no Docker
#          issuer-uri: http://localhost:8081/realms/mscourserealm   # Esta URL vem do Link do "OpenID Endpoint Configuration" do Keycloak informação "issuer"
#          issuer-uri: http://${KEYCLOAK_SERVER}:${KEYCLOAK_PORT}/realms/mscourserealm   # Esta URL vem do Link do "OpenID Endpoint Configuration" do Keycloak informação "issuer"
          issuer-uri: http://cursoms-keycloak:8080/realms/mscourserealm   # Esta URL vem do Link do "OpenID Endpoint Configuration" do Keycloak informação "issuer"

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: # http://<usuario>:<senha>@<url>:<porta>/eureka
      defaultZone: http://cursoms-eureka-user:ecok-usr-eeuramssur@${EUREKA_SERVER}:8761/eureka
#      defaultZone: http://cursoms-eureka-user:ecok-usr-eeuramssur@localhost:8761/eureka